import { Category, Transaction, DashboardStats } from '../types';

// 📂 CATEGORIAS MOCK
export const mockCategories: Category[] = [
  // Categorias de Gastos
  {
    id: '1',
    name: 'Alimentação',
    icon: 'restaurant',
    color: '#f59e0b',
    type: 'expense',
    isDefault: true,
    userId: 'user1',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Transporte',
    icon: 'car',
    color: '#3b82f6',
    type: 'expense',
    isDefault: true,
    userId: 'user1',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Moradia',
    icon: 'home',
    color: '#8b5cf6',
    type: 'expense',
    isDefault: true,
    userId: 'user1',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Saúde',
    icon: 'medical',
    color: '#ef4444',
    type: 'expense',
    isDefault: true,
    userId: 'user1',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Educação',
    icon: 'school',
    color: '#10b981',
    type: 'expense',
    isDefault: true,
    userId: 'user1',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Lazer',
    icon: 'game-controller',
    color: '#f97316',
    type: 'expense',
    isDefault: true,
    userId: 'user1',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Compras',
    icon: 'bag',
    color: '#ec4899',
    type: 'expense',
    isDefault: true,
    userId: 'user1',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  
  // Categorias de Receitas
  {
    id: '8',
    name: 'Salário',
    icon: 'wallet',
    color: '#16a34a',
    type: 'income',
    isDefault: true,
    userId: 'user1',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Freelance',
    icon: 'briefcase',
    color: '#0ea5e9',
    type: 'income',
    isDefault: true,
    userId: 'user1',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Investimentos',
    icon: 'trending-up',
    color: '#059669',
    type: 'income',
    isDefault: true,
    userId: 'user1',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '11',
    name: 'Outros',
    icon: 'ellipsis-horizontal',
    color: '#6b7280',
    type: 'both',
    isDefault: true,
    userId: 'user1',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// 💰 TRANSAÇÕES MOCK
export const mockTransactions: Transaction[] = [
  {
    id: '1',
    description: 'Supermercado',
    amount: 150.80,
    type: 'expense',
    categoryId: '1',
    category: mockCategories[0],
    date: new Date().toISOString(),
    notes: 'Compras da semana',
    userId: 'user1',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    description: 'Salário',
    amount: 3500.00,
    type: 'income',
    categoryId: '8',
    category: mockCategories[7],
    date: new Date(Date.now() - 86400000).toISOString(), // Ontem
    userId: 'user1',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    description: 'Uber',
    amount: 25.50,
    type: 'expense',
    categoryId: '2',
    category: mockCategories[1],
    date: new Date(Date.now() - 172800000).toISOString(), // 2 dias atrás
    userId: 'user1',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    description: 'Cinema',
    amount: 40.00,
    type: 'expense',
    categoryId: '6',
    category: mockCategories[5],
    date: new Date(Date.now() - 259200000).toISOString(), // 3 dias atrás
    notes: 'Filme com amigos',
    userId: 'user1',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    description: 'Freelance Design',
    amount: 800.00,
    type: 'income',
    categoryId: '9',
    category: mockCategories[8],
    date: new Date(Date.now() - 345600000).toISOString(), // 4 dias atrás
    notes: 'Logo para empresa',
    userId: 'user1',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// 📊 DASHBOARD STATS MOCK
export const mockDashboardStats: DashboardStats = {
  totalBalance: 4083.70,
  monthlyIncome: 4300.00,
  monthlyExpenses: 216.30,
  savingsRate: 94.97,
  expensesByCategory: [
    {
      categoryId: '1',
      categoryName: 'Alimentação',
      amount: 150.80,
      percentage: 69.7,
      color: '#f59e0b',
    },
    {
      categoryId: '6',
      categoryName: 'Lazer',
      amount: 40.00,
      percentage: 18.5,
      color: '#f97316',
    },
    {
      categoryId: '2',
      categoryName: 'Transporte',
      amount: 25.50,
      percentage: 11.8,
      color: '#3b82f6',
    },
  ],
  incomeVsExpenses: [
    { month: 'Jan', income: 3500, expenses: 1200 },
    { month: 'Fev', income: 3500, expenses: 1400 },
    { month: 'Mar', income: 3800, expenses: 1100 },
    { month: 'Abr', income: 4300, expenses: 216 },
  ],
  recentTransactions: mockTransactions.slice(0, 5),
  budgetStatus: [
    {
      budgetId: '1',
      budgetName: 'Alimentação',
      amount: 500,
      spent: 150.80,
      percentage: 30.16,
      status: 'ok',
    },
    {
      budgetId: '2',
      budgetName: 'Transporte',
      amount: 200,
      spent: 25.50,
      percentage: 12.75,
      status: 'ok',
    },
  ],
  upcomingGoals: [
    {
      id: '1',
      name: 'Viagem de Férias',
      description: 'Economizar para viagem',
      targetAmount: 5000,
      currentAmount: 1200,
      targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
      priority: 'high',
      status: 'active',
      reminders: [],
      userId: 'user1',
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
};

// 🔧 FUNÇÃO PARA SIMULAR DELAY DE API
export const simulateApiDelay = (ms: number = 1000) => {
  return new Promise(resolve => setTimeout(resolve, ms));
};